BEGIN;

DROP TABLE IF EXISTS "list",
    "card",
    "label",
    "card_has_label";


CREATE TABLE "list" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" text NOT NULL,
    "position" integer NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);


CREATE TABLE "card" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "content" text,
    "position" integer NOT NULL,
    "color" text,
    "list_id" integer NOT NULL REFERENCES "list"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);


CREATE TABLE "label" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text,
    "color" text,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);


CREATE TABLE "card_has_label" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text,
    "color" text,
    "card_id" integer NOT NULL REFERENCES "card"("id"),
    "label_id" integer NOT NULL REFERENCES "label"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

COMMIT;
